"""Generate a synthetic 802.11 capture.

This file exists so the analyzer is reproducible. A real capture from my own
hardware is the primary artifact (see docs/CAPTURE.md), but a pcap of a home
network is not something to commit to a public repository -- it contains the
MAC addresses of every device in the house -- and nobody cloning this repo
has a monitor-mode adapter to hand. So the committed sample is synthesised
from documentation-range addresses, and it is generated by code, which means
the analyzer's output can be checked against known ground truth in the tests.

Everything here is fabricated. No real network, device or handshake is
represented. Frames carry the right header fields and information elements;
payloads are filler, because the analyzer only ever reads metadata.

Scenario, chosen to exercise every detector:

  1. Three access points beacon: WPA2-PSK, WPA3-SAE, and a legacy TKIP AP.
  2. A station probes, open-authenticates and associates to the WPA2 AP.
  3. A four-way handshake completes; the AP leaks a PMKID in message 1.
  4. Encrypted data flows, with control frames interleaved.
  5. An attacker floods forged deauths at the station, spoofing the AP.
  6. The station reconnects and a second handshake is captured.
  7. A second station does SAE authentication against the WPA3 AP.
  8. An "evil twin" beacons the WPA2 network's SSID with no security at all.
"""

import struct

from scapy.layers.dot11 import (  # type: ignore[import-untyped]
    Dot11,
    Dot11AssoReq,
    Dot11AssoResp,
    Dot11Auth,
    Dot11Beacon,
    Dot11Deauth,
    Dot11Elt,
    Dot11ProbeReq,
    Dot11ProbeResp,
    RadioTap,
)
from scapy.layers.eap import EAPOL  # type: ignore[import-untyped]
from scapy.layers.l2 import LLC, SNAP  # type: ignore[import-untyped]
from scapy.packet import Raw  # type: ignore[import-untyped]
from scapy.utils import wrpcap  # type: ignore[import-untyped]

from .eapol import (
    KEY_INFO_ACK,
    KEY_INFO_ENCRYPTED,
    KEY_INFO_INSTALL,
    KEY_INFO_MIC,
    KEY_INFO_PAIRWISE,
    KEY_INFO_SECURE,
)
from .rsn import build_rsn_element

# Locally administered addresses (the 0x02 bit is set), so none of these can
# collide with a real manufacturer-assigned MAC.
AP_WPA2 = "02:00:00:aa:00:01"
AP_WPA3 = "02:00:00:bb:00:01"
AP_LEGACY = "02:00:00:cc:00:01"
AP_EVIL_TWIN = "02:00:00:de:ad:01"
STA_ONE = "02:00:00:11:11:11"
STA_TWO = "02:00:00:22:22:22"
ATTACKER = "02:00:00:66:66:66"
BROADCAST = "ff:ff:ff:ff:ff:ff"

SSID_WPA2 = "TestNet-WPA2"
SSID_WPA3 = "TestNet-WPA3"
SSID_LEGACY = "TestNet-Legacy"

CHANNEL_FREQUENCIES = {1: 2412, 6: 2437, 11: 2462, 36: 5180}

# Fabricated nonces and PMKID. Fixed, not random, so the capture is
# byte-identical on every regeneration and the tests can assert on it.
ANONCE_1 = bytes.fromhex("a1" * 32)
SNONCE_1 = bytes.fromhex("51" * 32)
ANONCE_2 = bytes.fromhex("a2" * 32)
SNONCE_2 = bytes.fromhex("52" * 32)
PMKID = bytes.fromhex("0123456789abcdef0123456789abcdef")


def _radiotap(channel: int, signal: int) -> RadioTap:
    """Radiotap header, as a capturing adapter would prepend."""
    frequency = CHANNEL_FREQUENCIES.get(channel, 2437)
    flags = "5GHz+OFDM" if frequency > 3000 else "2GHz+CCK"
    return RadioTap(
        present="Channel+dBm_AntSignal",
        ChannelFrequency=frequency,
        ChannelFlags=flags,
        dBm_AntSignal=signal,
    )


def _elements(ssid: str, channel: int, rsn: bytes | None) -> Dot11Elt:
    """Standard beacon element chain: SSID, rates, DS parameter, RSN."""
    chain = Dot11Elt(ID=0, info=ssid.encode())
    chain /= Dot11Elt(ID=1, info=b"\x82\x84\x8b\x96\x0c\x12\x18\x24")  # rates
    chain /= Dot11Elt(ID=3, info=bytes([channel]))  # DS parameter set
    if rsn is not None:
        chain /= Dot11Elt(ID=48, info=rsn)
    return chain


def _beacon(bssid: str, ssid: str, channel: int, rsn: bytes | None, signal: int):
    frame = Dot11(
        type=0, subtype=8, addr1=BROADCAST, addr2=bssid, addr3=bssid
    )
    # cap=0x1101: ESS, Privacy, Short Preamble. Privacy must be set whenever
    # an RSN element is present, and clear on the open evil twin.
    capability = 0x1101 if rsn is not None else 0x1001
    body = Dot11Beacon(beacon_interval=100, cap=capability)
    return _radiotap(channel, signal) / frame / body / _elements(ssid, channel, rsn)


def _eapol_key(
    key_info: int,
    replay_counter: int,
    nonce: bytes,
    key_data: bytes = b"",
    key_mic: bytes = b"\x00" * 16,
) -> bytes:
    """Assemble an EAPOL-Key body per IEEE 802.11-2020 Figure 12-33.

    The MIC is filler. Computing a real one needs the PTK, which needs the
    passphrase, and this project deliberately never derives key material from
    a passphrase. The analyzer reads flag bits, counters and nonces, none of
    which depend on the MIC being valid.
    """
    body = bytes([2])  # descriptor type: RSN
    body += struct.pack("!HH", key_info, 16)  # key info, key length
    body += struct.pack("!Q", replay_counter)
    body += nonce
    body += b"\x00" * 16  # key IV
    body += b"\x00" * 8  # key RSC
    body += b"\x00" * 8  # reserved
    body += key_mic
    body += struct.pack("!H", len(key_data))
    body += key_data
    return body


def _pmkid_kde(pmkid: bytes) -> bytes:
    """A PMKID KDE: vendor element 221, OUI 00-0F-AC, data type 4."""
    payload = b"\x00\x0f\xac\x04" + pmkid
    return bytes([221, len(payload)]) + payload


def _eapol_frame(source: str, destination: str, bssid: str, body: bytes,
                 from_ds: bool, channel: int, signal: int):
    """Wrap an EAPOL-Key body in a data frame addressed through the AP."""
    if from_ds:
        dot11 = Dot11(type=2, subtype=0, FCfield="from_DS",
                      addr1=destination, addr2=bssid, addr3=source)
    else:
        dot11 = Dot11(type=2, subtype=0, FCfield="to_DS",
                      addr1=bssid, addr2=source, addr3=destination)
    # A data frame carries EAPOL inside an LLC/SNAP header: DSAP/SSAP 0xAA
    # with control 0x03, then OUI 00-00-00 and EtherType 0x888E. Omitting
    # this is the classic mistake when synthesising 802.11 data frames --
    # the bytes look plausible but no dissector will find the EAPOL layer.
    llc = LLC(dsap=0xAA, ssap=0xAA, ctrl=3) / SNAP(OUI=0, code=0x888E)
    eapol = EAPOL(version=2, type=3, len=len(body))
    return _radiotap(channel, signal) / dot11 / llc / eapol / Raw(load=body)


def _data(source: str, destination: str, bssid: str, from_ds: bool,
          channel: int, signal: int, size: int = 128):
    """A protected QoS data frame. Payload is filler standing in for ciphertext."""
    if from_ds:
        dot11 = Dot11(type=2, subtype=8, FCfield="from_DS+protected",
                      addr1=destination, addr2=bssid, addr3=source)
    else:
        dot11 = Dot11(type=2, subtype=8, FCfield="to_DS+protected",
                      addr1=bssid, addr2=source, addr3=destination)
    return _radiotap(channel, signal) / dot11 / Raw(load=b"\xcc" * size)


def _ack(receiver: str, channel: int, signal: int):
    """An ACK: control subtype 13, and the only address is the receiver."""
    return _radiotap(channel, signal) / Dot11(type=1, subtype=13, addr1=receiver)


def _rts(receiver: str, transmitter: str, channel: int, signal: int):
    return _radiotap(channel, signal) / Dot11(
        type=1, subtype=11, addr1=receiver, addr2=transmitter
    )


def _cts(receiver: str, channel: int, signal: int):
    return _radiotap(channel, signal) / Dot11(type=1, subtype=12, addr1=receiver)


def _block_ack(receiver: str, transmitter: str, channel: int, signal: int):
    return _radiotap(channel, signal) / Dot11(
        type=1, subtype=9, addr1=receiver, addr2=transmitter
    ) / Raw(load=b"\x00" * 10)


def build_capture() -> list:
    """Build the full frame list with timestamps. Returns scapy packets."""
    packets: list = []
    clock = [1_700_000_000.0]  # fixed epoch: the capture is deterministic

    def emit(packet, step: float = 0.002):
        clock[0] += step
        packet.time = clock[0]
        packets.append(packet)
        return packet

    rsn_wpa2 = build_rsn_element(akm_suites=(2,))  # PSK, CCMP, no MFP
    rsn_wpa3 = build_rsn_element(
        akm_suites=(8,), mfp_capable=True, mfp_required=True, group_mgmt_cipher=6
    )
    rsn_legacy = build_rsn_element(group_cipher=2, pairwise_ciphers=(2, 4))  # TKIP

    # --- 1. Beacons from three networks -------------------------------------
    for round_index in range(6):
        emit(_beacon(AP_WPA2, SSID_WPA2, 6, rsn_wpa2, -42), 0.1024)
        emit(_beacon(AP_WPA3, SSID_WPA3, 36, rsn_wpa3, -55), 0.0016)
        emit(_beacon(AP_LEGACY, SSID_LEGACY, 11, rsn_legacy, -71), 0.0016)

    # --- 2. Station one discovers and joins the WPA2 network ----------------
    emit(_radiotap(6, -38) / Dot11(type=0, subtype=4, addr1=BROADCAST,
                                   addr2=STA_ONE, addr3=BROADCAST)
         / Dot11ProbeReq() / Dot11Elt(ID=0, info=b"")  # wildcard SSID
         , 0.05)
    emit(_ack(STA_ONE, 6, -38), 0.0001)
    emit(_radiotap(6, -42) / Dot11(type=0, subtype=5, addr1=STA_ONE,
                                   addr2=AP_WPA2, addr3=AP_WPA2)
         / Dot11ProbeResp(beacon_interval=100, cap=0x1101)
         / _elements(SSID_WPA2, 6, rsn_wpa2), 0.004)

    # Open System authentication: WPA2-PSK does not authenticate here at all,
    # it just says "yes" -- the real check is the four-way handshake later.
    emit(_radiotap(6, -38) / Dot11(type=0, subtype=11, addr1=AP_WPA2,
                                   addr2=STA_ONE, addr3=AP_WPA2)
         / Dot11Auth(algo=0, seqnum=1, status=0), 0.01)
    emit(_radiotap(6, -42) / Dot11(type=0, subtype=11, addr1=STA_ONE,
                                   addr2=AP_WPA2, addr3=AP_WPA2)
         / Dot11Auth(algo=0, seqnum=2, status=0), 0.003)
    emit(_radiotap(6, -38) / Dot11(type=0, subtype=0, addr1=AP_WPA2,
                                   addr2=STA_ONE, addr3=AP_WPA2)
         / Dot11AssoReq(cap=0x1101, listen_interval=10)
         / _elements(SSID_WPA2, 6, rsn_wpa2), 0.005)
    emit(_radiotap(6, -42) / Dot11(type=0, subtype=1, addr1=STA_ONE,
                                   addr2=AP_WPA2, addr3=AP_WPA2)
         / Dot11AssoResp(cap=0x1101, status=0, AID=1), 0.004)

    # --- 3. Four-way handshake, with a PMKID leaked in message 1 ------------
    _four_way(emit, ANONCE_1, SNONCE_1, include_pmkid=True, counter_base=1)

    # --- 4. Data exchange with control frames -------------------------------
    for index in range(10):
        emit(_data(STA_ONE, AP_WPA2, AP_WPA2, from_ds=False, channel=6,
                   signal=-39, size=96 + index * 8), 0.012)
        emit(_ack(STA_ONE, 6, -39), 0.0001)
        emit(_data(AP_WPA2, STA_ONE, AP_WPA2, from_ds=True, channel=6,
                   signal=-43, size=512), 0.003)
        emit(_ack(AP_WPA2, 6, -43), 0.0001)
        if index % 4 == 0:
            emit(_rts(AP_WPA2, STA_ONE, 6, -39), 0.0008)
            emit(_cts(STA_ONE, 6, -43), 0.0001)
        if index % 5 == 4:
            emit(_block_ack(STA_ONE, AP_WPA2, 6, -43), 0.0006)

    # --- 5. Deauthentication flood, spoofing the AP -------------------------
    # The attacker transmits with the AP's address in addr2. Nothing in an
    # unprotected deauth prevents that: there is no MIC and no sequence
    # binding, so the frame is indistinguishable from a genuine one at the
    # receiver. Reason 7 ("class 3 frame from nonassociated STA") is the
    # usual choice because clients act on it immediately.
    for burst in range(12):
        emit(_radiotap(6, -50) / Dot11(type=0, subtype=12, addr1=STA_ONE,
                                       addr2=AP_WPA2, addr3=AP_WPA2)
             / Dot11Deauth(reason=7), 0.05)
        emit(_radiotap(6, -50) / Dot11(type=0, subtype=12, addr1=BROADCAST,
                                       addr2=AP_WPA2, addr3=AP_WPA2)
             / Dot11Deauth(reason=7), 0.02)

    # --- 6. The station reconnects; a second handshake is captured ----------
    emit(_radiotap(6, -38) / Dot11(type=0, subtype=11, addr1=AP_WPA2,
                                   addr2=STA_ONE, addr3=AP_WPA2)
         / Dot11Auth(algo=0, seqnum=1, status=0), 0.4)
    emit(_radiotap(6, -42) / Dot11(type=0, subtype=11, addr1=STA_ONE,
                                   addr2=AP_WPA2, addr3=AP_WPA2)
         / Dot11Auth(algo=0, seqnum=2, status=0), 0.003)
    emit(_radiotap(6, -38) / Dot11(type=0, subtype=0, addr1=AP_WPA2,
                                   addr2=STA_ONE, addr3=AP_WPA2)
         / Dot11AssoReq(cap=0x1101, listen_interval=10)
         / _elements(SSID_WPA2, 6, rsn_wpa2), 0.005)
    emit(_radiotap(6, -42) / Dot11(type=0, subtype=1, addr1=STA_ONE,
                                   addr2=AP_WPA2, addr3=AP_WPA2)
         / Dot11AssoResp(cap=0x1101, status=0, AID=1), 0.004)
    _four_way(emit, ANONCE_2, SNONCE_2, include_pmkid=False, counter_base=5)

    # --- 7. WPA3: SAE authentication on the 5 GHz AP ------------------------
    # Authentication algorithm 3 is SAE. Unlike Open System above, these two
    # frames carry the actual Dragonfly commit and confirm exchange -- the
    # password-authenticated key exchange happens here, before association,
    # which is why WPA3 has no offline dictionary exposure.
    emit(_radiotap(36, -57) / Dot11(type=0, subtype=11, addr1=AP_WPA3,
                                    addr2=STA_TWO, addr3=AP_WPA3)
         / Dot11Auth(algo=3, seqnum=1, status=0)
         / Raw(load=b"\x13\x00" + b"\x5a" * 96), 0.3)   # commit
    emit(_radiotap(36, -55) / Dot11(type=0, subtype=11, addr1=STA_TWO,
                                    addr2=AP_WPA3, addr3=AP_WPA3)
         / Dot11Auth(algo=3, seqnum=1, status=0)
         / Raw(load=b"\x13\x00" + b"\x6b" * 96), 0.006)
    emit(_radiotap(36, -57) / Dot11(type=0, subtype=11, addr1=AP_WPA3,
                                    addr2=STA_TWO, addr3=AP_WPA3)
         / Dot11Auth(algo=3, seqnum=2, status=0)
         / Raw(load=b"\x00" * 34), 0.004)               # confirm
    emit(_radiotap(36, -55) / Dot11(type=0, subtype=11, addr1=STA_TWO,
                                    addr2=AP_WPA3, addr3=AP_WPA3)
         / Dot11Auth(algo=3, seqnum=2, status=0)
         / Raw(load=b"\x00" * 34), 0.004)
    emit(_radiotap(36, -57) / Dot11(type=0, subtype=0, addr1=AP_WPA3,
                                    addr2=STA_TWO, addr3=AP_WPA3)
         / Dot11AssoReq(cap=0x1111, listen_interval=10)
         / _elements(SSID_WPA3, 36, rsn_wpa3), 0.005)
    emit(_radiotap(36, -55) / Dot11(type=0, subtype=1, addr1=STA_TWO,
                                    addr2=AP_WPA3, addr3=AP_WPA3)
         / Dot11AssoResp(cap=0x1111, status=0, AID=2), 0.004)
    for index in range(4):
        emit(_data(STA_TWO, AP_WPA3, AP_WPA3, from_ds=False, channel=36,
                   signal=-56, size=160), 0.02)
        emit(_ack(STA_TWO, 36, -56), 0.0001)

    # --- 8. Evil twin: the WPA2 SSID, beaconed with no security -------------
    for _ in range(5):
        emit(_beacon(AP_EVIL_TWIN, SSID_WPA2, 6, None, -33), 0.1024)

    # A deauth from the attacker's own address, aimed at pushing the station
    # onto the open clone.
    for _ in range(3):
        emit(_radiotap(6, -33) / Dot11(type=0, subtype=12, addr1=STA_ONE,
                                       addr2=ATTACKER, addr3=ATTACKER)
             / Dot11Deauth(reason=1), 0.03)

    return packets


def _four_way(emit, anonce: bytes, snonce: bytes, include_pmkid: bool,
              counter_base: int) -> None:
    """Emit one complete four-way handshake between STA_ONE and AP_WPA2."""
    key_data_m1 = _pmkid_kde(PMKID) if include_pmkid else b""

    # M1: AP -> STA. ANonce, Ack set, no MIC (the STA has no PTK yet).
    emit(_eapol_frame(
        AP_WPA2, STA_ONE, AP_WPA2,
        _eapol_key(KEY_INFO_PAIRWISE | KEY_INFO_ACK, counter_base, anonce,
                   key_data_m1),
        from_ds=True, channel=6, signal=-42), 0.02)
    emit(_ack(AP_WPA2, 6, -42), 0.0001)

    # M2: STA -> AP. SNonce plus the station's RSN element, MIC now present.
    emit(_eapol_frame(
        STA_ONE, AP_WPA2, AP_WPA2,
        _eapol_key(KEY_INFO_PAIRWISE | KEY_INFO_MIC, counter_base, snonce,
                   bytes([48, len(build_rsn_element(akm_suites=(2,)))])
                   + build_rsn_element(akm_suites=(2,)),
                   key_mic=b"\x0a" * 16),
        from_ds=False, channel=6, signal=-38), 0.008)
    emit(_ack(STA_ONE, 6, -38), 0.0001)

    # M3: AP -> STA. Install + Secure set; key data is encrypted under the KEK.
    emit(_eapol_frame(
        AP_WPA2, STA_ONE, AP_WPA2,
        _eapol_key(
            KEY_INFO_PAIRWISE | KEY_INFO_ACK | KEY_INFO_MIC
            | KEY_INFO_SECURE | KEY_INFO_INSTALL | KEY_INFO_ENCRYPTED,
            counter_base + 1, anonce, b"\xee" * 56, key_mic=b"\x0b" * 16),
        from_ds=True, channel=6, signal=-42), 0.007)
    emit(_ack(AP_WPA2, 6, -42), 0.0001)

    # M4: STA -> AP. Zero nonce, Secure set, no key data. Handshake done.
    emit(_eapol_frame(
        STA_ONE, AP_WPA2, AP_WPA2,
        _eapol_key(KEY_INFO_PAIRWISE | KEY_INFO_MIC | KEY_INFO_SECURE,
                   counter_base + 1, b"\x00" * 32, key_mic=b"\x0c" * 16),
        from_ds=False, channel=6, signal=-38), 0.006)
    emit(_ack(STA_ONE, 6, -38), 0.0001)


def write_capture(path: str) -> int:
    """Generate the capture and write it to `path`. Returns the frame count."""
    packets = build_capture()
    wrpcap(path, packets)
    return len(packets)


if __name__ == "__main__":
    import sys

    target = sys.argv[1] if len(sys.argv) > 1 else "captures/synthetic.pcap"
    count = write_capture(target)
    print(f"wrote {count} frames to {target}")
