"""Finite-field Diffie-Hellman group parameters and validation.

Groups are the MODP groups from RFC 3526. Each modulus p is a *safe prime*
(p = 2q + 1 with q prime), so the multiplicative group mod p has exactly one
large prime-order subgroup of order q plus the trivial subgroup {1, p-1}.
That structure is what makes the public-key validation in `dh.py` cheap and
complete: a single exponentiation decides subgroup membership.
"""

from dataclasses import dataclass


def _h(text: str) -> int:
    """Parse a hex modulus written with whitespace, as RFC 3526 prints them."""
    return int("".join(text.split()), 16)


# RFC 3526 Section 3 -- 2048-bit MODP Group (id 14).
_P_2048 = _h(
    """
    FFFFFFFF FFFFFFFF C90FDAA2 2168C234 C4C6628B 80DC1CD1
    29024E08 8A67CC74 020BBEA6 3B139B22 514A0879 8E3404DD
    EF9519B3 CD3A431B 302B0A6D F25F1437 4FE1356D 6D51C245
    E485B576 625E7EC6 F44C42E9 A637ED6B 0BFF5CB6 F406B7ED
    EE386BFB 5A899FA5 AE9F2411 7C4B1FE6 49286651 ECE45B3D
    C2007CB8 A163BF05 98DA4836 1C55D39A 69163FA8 FD24CF5F
    83655D23 DCA3AD96 1C62F356 208552BB 9ED52907 7096966D
    670C354E 4ABC9804 F1746C08 CA18217C 32905E46 2E36CE3B
    E39E772C 180E8603 9B2783A2 EC07A28F B5C55DF0 6F4C52C9
    DE2BCBF6 95581718 3995497C EA956AE5 15D22618 98FA0510
    15728E5A 8AACAA68 FFFFFFFF FFFFFFFF
    """
)

# RFC 3526 Section 4 -- 3072-bit MODP Group (id 15).
_P_3072 = _h(
    """
    FFFFFFFF FFFFFFFF C90FDAA2 2168C234 C4C6628B 80DC1CD1
    29024E08 8A67CC74 020BBEA6 3B139B22 514A0879 8E3404DD
    EF9519B3 CD3A431B 302B0A6D F25F1437 4FE1356D 6D51C245
    E485B576 625E7EC6 F44C42E9 A637ED6B 0BFF5CB6 F406B7ED
    EE386BFB 5A899FA5 AE9F2411 7C4B1FE6 49286651 ECE45B3D
    C2007CB8 A163BF05 98DA4836 1C55D39A 69163FA8 FD24CF5F
    83655D23 DCA3AD96 1C62F356 208552BB 9ED52907 7096966D
    670C354E 4ABC9804 F1746C08 CA18217C 32905E46 2E36CE3B
    E39E772C 180E8603 9B2783A2 EC07A28F B5C55DF0 6F4C52C9
    DE2BCBF6 95581718 3995497C EA956AE5 15D22618 98FA0510
    15728E5A 8AAAC42D AD33170D 04507A33 A85521AB DF1CBA64
    ECFB8504 58DBEF0A 8AEA7157 5D060C7D B3970F85 A6E1E4C7
    ABF5AE8C DB0933D7 1E8C94E0 4A25619D CEE3D226 1AD2EE6B
    F12FFA06 D98A0864 D8760273 3EC86A64 521F2B18 177B200C
    BBE11757 7A615D6C 770988C0 BAD946E2 08E24FA0 74E5AB31
    43DB5BFC E0FD108E 4B82D120 A93AD2CA FFFFFFFF FFFFFFFF
    """
)


@dataclass(frozen=True)
class DHGroup:
    """A MODP group with a safe-prime modulus.

    Attributes:
        group_id: The IANA / RFC 3526 group number, carried on the wire.
        p: The prime modulus.
        g: The generator (2 for every RFC 3526 group).
        bits: Size of p, used to fix the padded length of encoded values.
    """

    group_id: int
    p: int
    g: int
    bits: int

    @property
    def q(self) -> int:
        """Order of the large prime-order subgroup generated by g."""
        return (self.p - 1) // 2

    @property
    def size_bytes(self) -> int:
        """Fixed encoding width for public keys and the shared secret.

        Every field element is padded to this width so that the transcript
        hash and the key schedule never depend on the leading-zero count of a
        particular value.
        """
        return (self.bits + 7) // 8


MODP_2048 = DHGroup(group_id=14, p=_P_2048, g=2, bits=2048)
MODP_3072 = DHGroup(group_id=15, p=_P_3072, g=2, bits=3072)

GROUPS = {g.group_id: g for g in (MODP_2048, MODP_3072)}

DEFAULT_GROUP = MODP_2048


def get_group(group_id: int) -> DHGroup:
    """Look up a group by its wire identifier.

    Refusing unknown identifiers is the point: a peer must not be able to
    steer us into a group we have not vetted, which is how downgrade attacks
    on negotiated-group protocols usually start.
    """
    try:
        return GROUPS[group_id]
    except KeyError:
        raise ValueError(f"unsupported DH group id {group_id}") from None
